### ISSUE TITLE
Build tasks automation

### ISSUE THREAD

**Issue by bryanmullin** [alefragnani/vscode-language-pascal#10]
Instead of copy/pasting the same build tasks into tasks.json for every pascal project folder that a user has, have you found any way to automate the process?
For example:  A user has a fully functional build script that points to DCC32.exe, is there a way for the extension to automatically create a tasks.json with those parameters to each created pascal project?

**Comment by alefragnani** [comment]
Hi @bryanmullin ,

Instead of copy/paste, you could create _snippets_ for the build tasks. It should be simpler/easier to use.

When you say _functional build task_ I guess you're talking about a `.dproj` file in root folder? If yes, I have an idea :smile:

**Comment by alefragnani** [comment]
- [ ] Add a setting for _compiler path_
- [ ] Add a setting for _compiler type_ (delphi, fpc)
- [ ] Add a command to generate build task (autocomplete compiler path and project file)

**Comment by pakLebah** [comment]
I simply copy the same `tasks.json` file to `.vscode` folder into my pascal workspaces. The tasks work with every pascal file. Here's my pascal tasks collection in a [gist](http://gist.github.com/pakLebah/dab98067e9a3…). 

Please note that I work with Free Pascal, not Delphi. So, if you want to use it with Delphi, you have to change the compiler parameters accordingly.

**Comment by alwayzoverdozed** [comment]
well i don't know how i even got here but thank you!!

**Comment by alefragnani** [comment]
I'm closing this feature request because it didn’t receive enough upvotes from the community. Still a big Thank You to you for taking the time to create this issue!

Thanks for your understanding
