### ISSUE TITLE
Update README.md to support othere file ext in FreePascal build task snippet

### ISSUE THREAD

**Issue by nilya** [alefragnani/vscode-language-pascal#14]
Regex pattern uses ".p" file extension, but the ".pas" is commonly used.
```diff
-                "regexp": "^([\\w]+\\.p)\\((\\d+)\\,(\\d+)\\)\\s(Fatal|Error|Warning|Note):(.*)",
+                "regexp": "^([\\w]+\\.pas)\\((\\d+)\\,(\\d+)\\)\\s(Fatal|Error|Warning|Note):(.*)",
```
Maybe change or add this extension too?

**Comment by alefragnani** [comment]
Hi @nilya ,

This section in `README.md` is just an example 😄 

I used `.p` because remembering somehow that `.p` was the default extension in FreePascal. Since it also supports `.pp` and `.pas`, it should be better to have `"^([\\w]+\\.(p|pp|pas))` instead (supporting all extensions).
