### ISSUE TITLE
[BUG] - Paren comments (* do not properly auto-close

### ISSUE THREAD

**Issue by CharlesAverill** [alefragnani/vscode-language-pascal#141]
**Environment/version**

- Extension version: `v9.6.0`
- VSCode version: 
```
$ code --version
1.83.0
e7e037083ff4455cf320e344325dacb480062c3c
x64
```
- OS version:
```
$ neofetch --stdout
--------------------- 
OS: Pop!_OS 22.04 LTS x86_64 
Kernel: 6.2.0-76060200-generic 
```

**Steps to reproduce**

Paren comments `(*` are autoclosed with `)` instead of `*)`, likely because the textmate language is greedily matching `(` first. Not sure if there's a fix for this, I haven't dealt with the xml form of tmlanguages before.

**Comment by alefragnani** [comment]
Hi @CharlesAverill ,

First of all, sorry for the late reply. 

About the issue, in fact, I guess it is not related to `.tmlanguage` at all, as the auto closing pairs are defined in a separate file (`pascal.configuration.json`). Simply adding a new entry `["(*", "*)"],` seems to work just fine.

It should be available in the next release.

Thanks for reporting

**Comment by CharlesAverill** [comment]
Thank you so much!
