### ISSUE TITLE
[BUG] - no exe

### ISSUE THREAD

**Issue by witchanto** [alefragnani/vscode-language-pascal#155]
**Environment/version**

- Extension version: 9.8
- VSCode version: October 2024
- OS version: 

**Steps to reproduce**
I want to make exe-files, no matter if windows 64 bit or Mac 15.
but there is no exe-file created and for the syntax colour I needed 
more than 1 marketplace extensions, which were hard to solve to 
get the colors.
so for what is your pascal? if some extensions additional to your 
always asking for fpc? and fpc can not be started on Mac 15.

**Comment by alefragnani** [comment]
Hi @witchanto ,

This extension is focused on syntax highlight, snippets and navigation, not for compiling/building apps. It has mentions to Tasks, so you can compile and build apps using FPC or Delphi, but it is not the intention of the extension.

Most of the times, extensions tends to use references of already installed language tools / sdks. I don’t work with FPC, and I’m not sure there is an extension that supports FPC out of the box. Delphi, on the other hand, has its own extension now, but it only works on Windows (as Delphi itself is Windows only).

If you need to compile/build apps in VS Code, and use this extension, the approach is to use Tasks, as commented here (https://github.com/alefragnani/vscode-language-pascal#task-build). Tasks are a VS Code concept, and may be used for any language / extension, with no direct connection to FPC or Delphi.

Hope this helps

**Comment by witchanto** [comment]
first, this is a good explaination. 
i tried to add this task build, but in which filename is to write these Json(with the { and [ )? ?
is DCC32.EXE_PATH this by embarcadero?

**Comment by alefragnani** [comment]
You may have more info about VS Code tasks here https://code.visualstudio.com/docs/editor/tasks#vscode.

The file should be located in `.vscode/tasks.json`, and the `DCC32.EXE_PATH` is indeed from Embarcadero. The Delphi compiler (dcc32.exe) path. Just like `FPC_BIN_PATH` refers to the path of the FPC compiler.

Hope this helps
