### ISSUE TITLE
The filename, directory name, or volume label syntax is incorrect.

### ISSUE THREAD

**Issue by mtr2014** [alefragnani/vscode-language-pascal#20]
I created the tasks.json but when i try to Run Task Build I get "The filename, directory name, or volume label syntax is incorrect."

"command": "‪C:\\FPC\\3.0.2\\bin\\i386-win32\\fpc.exe"

"args": ["‪C:\\Users\\me\\Desktop\\helloworld.pas"]

Is maybe something wrong with my paths?

**Comment by alefragnani** [comment]
Hi @mtr2014 ,

You must remember to use **double slashes** while defining paths (on Windows). For instance:

```
   "command": "C:\\lazarus\\fpc\\3.0.0\\bin\\i386-win32\\fpc.exe",
    "args": ["C:\\Users\\me\\Desktop\\helloworld.pas"]
```` 

Just a note, you now can also use [Variable Substitution](https://code.visualstudio.com/docs/editor/tasks#_variable-substitution) so you don't have to define the _specific file_ on your `tasks.json` file, but use _the current opened file_ `${file}`. It may make your life easier for building projects.
               
This is a `tasks.json` that I have defined on one of my sample projects:

```
{
 "version": "0.1.0",
 
 "windows": {
	 "command": "C:\\lazarus\\fpc\\3.0.0\\bin\\i386-win32\\fpc.exe"
  },
 "isShellCommand": true,
 "showOutput": "always",
 "args": ["${file}"],
 "problemMatcher": {
	 "owner": "external",
	 "pattern": {
		 "regexp": "^([\\w]+\\.(p|pp|pas))\\((\\d+)\\,(\\d+)\\)\\s(Fatal|Error|Warning|Note):(.*)",
		 "file": 1,
		 "line": 3,
		 "column": 4,
		 "message": 5
	 }
 }
}
```

Hope this helps
