### ISSUE TITLE
Breakpoints totally disabled?

### ISSUE THREAD

**Issue by genericptr** [alefragnani/vscode-language-pascal#27]
I'm testing Visual Studio Code now (1.21.1 for Mac) and got it working just fine using C++ (debugging, building, breakpoints). Now I'm trying to setup a Pascal project using the extension "Language Pascal" but breakpoints seem to be entirely disabled, i.e. clicking in gutter doesn't toggle anything, "Debug > Toggle Breakpoint" menu doesn't work either (nothing is added in the breakpoints pane).

Is this a bug or does the extension have to explicitly opt into breakpoints? Creating a new empty file has breakpoints disabled also so maybe I'm missing something.

Sorry if this is a bad place to ask questions but I didn't know where else to go. Thanks in advance.

**Comment by alefragnani** [comment]
Hi @genericptr ,

The breakpoints are disabled because the extension _does not support_ it, until Embarcadero opens up any API/Library for that. 

You could try [this extension](https://marketplace.visualstudio.com/items?itemName=webfreak.debug), that appears to be working for some scenarios, but I personally didn't use it.

Hope this helps

**Comment by genericptr** [comment]
Thanks that's fixed the problem and enabled the breakpoints. Why can't the extension support breakpoints as-is? I'm on Mac and using LLDB works just fine without any additional API's so I think leaving them on by default would be helpful.

**Comment by alefragnani** [comment]
It's not a matter of _leaving them on by default_, but _to support it_. 

Embarcadero did not opened its debugger, yet, so I don't intend do add that on the extension. That extension supports GDB/LDDB debuggers, which are available only for FreePascal, which I _just play_ with (I'm a fulltime Delphi developer). BTW, I tried to use FreePascal on Windows and discovered that its debugger is weak (it fails even in `strings`) compared to other platforms.

If Embarcadero opens its debugger, I'll certainly take a look to include support it.
