### ISSUE TITLE
Support Code Completion

### ISSUE THREAD

**Issue by shoorlyne** [alefragnani/vscode-language-pascal#33]
Hello!

Do you plan to add support for completion support in the near future?

Thanks!

**Comment by alefragnani** [comment]
Hi @shoorlyne ,

First of all, sorry for taking so long to answer you. The last weeks has been a busy period and I'm not being able to give proper attention to my projects.

About the Completion support, I would like to say _"yes, I will"_, but I don't know for sure. To add completion support would require redesign how I handle document symbols, and for that, a considerable amount of effort.

Last week I decided to "re-focus" on some of my extensions, and I'll start to plan milestones for each of them. This "re-focus" will be based on community feedback/support.

What do you think about it?

**Comment by shoorlyne** [comment]
Awesome, keep up the good work!

**Comment by alefragnani** [comment]
I'm closing this feature request because it didn’t receive enough upvotes from the community. Still a big Thank You to you for taking the time to create this issue!

Thanks for your understanding
