### ISSUE TITLE
Support other Document Symbols (variables, interfaces, classes)

### ISSUE THREAD

**Issue by yqmmm** [alefragnani/vscode-language-pascal#35]
Hello, thanks for the great work first.

I am new to these tagging tools. I noticed that navigation only works for procedure and function, not variable. I've tried to use the `global -f` command and there is no variable. So is my configuration wrong or this is the supposed behavior? I've tried to built [Pygments Plug-in Parser for GLOBAL](https://github.com/yoshizow/global-pygments-plugin), but it din't work.

**Comment by alefragnani** [comment]
Hi @yqmmm ,

First of all, thank you 👍 

You are right. The navigation is limited to functions and procedures. The tagging tools does not support recognition of other symbols like variables and constants.

As [commented here](https://github.com/alefragnani/vscode-language-pascal/issues/33#issuecomment-422207235), it would require a redesign in the extension. Unfortunately, there is no ETA for that right now.

Hope this helps

**Comment by alefragnani** [comment]
I'm closing this feature request because it didn’t receive enough upvotes from the community. Still a big Thank You to you for taking the time to create this issue!

Thanks for your understanding
