### ISSUE TITLE
Language Services - Go to Definition

### ISSUE THREAD

**Issue by alefragnani** [alefragnani/vscode-language-pascal#4]
Add **Go to Definition**

**Comment by bryanmullin** [comment]
Will this be implementing the Ctrl+shift+O function that creates go-to symbols?

**Comment by alefragnani** [comment]
Hi @bryanmullin ,

No, this is related to **F12** in VS Code, which _goes where that identifier is defined_. It's like **Ctrl + Click**  in Delphi.

`Ctrl + Shift + O` is already possible. You just have to follow the instructions defined in `README.md` [link](https://github.com/alefragnani/vscode-language-pascal#go-to-symbol).

Hope this helps.

**Comment by alefragnani** [comment]
🏃

**Comment by alefragnani** [comment]
Hi @regs01 ,

First, let's see if `gtags` and `global` are working. To this, 

1. Open **Command Prompt**
2. Navigate to the same folder you opened in VS Code
3. Run `gtags`
4. The _output_ should be nothing or something like below, which I'm not sure when this _warning_ started
```
C:\Apps\glo6612wb\bin\../share/gtags/script/pygments_parser.py:92: SyntaxWarning: invalid escape sequence '\s'
  tag = re.sub('\s+', '', tag)    # remove newline and spaces
C:\Apps\glo6612wb\bin\../share/gtags/script/pygments_parser.py:161: SyntaxWarning: invalid escape sequence '\s'
  match = re.search(r'(\S+)\s+(\d+)\s+' + re.escape(path) + '\s+(.*)$', line)
```
5. Run `global -f .\pathto\Unit1.pas
6. The _output_ should be each `method` within the file in a format of `MethodName lineNumber pathToUnit1.pas MethodDeclaration`, like:
```
DoSomething 24 .\src\Unit1.pas procedure DoSomething(const AIndex: Integer);
...
```

If steps 3 of 5 does not produce the outputs in steps 4 or 6, then `global` or `gtags` are not working.

If everything is working in **Command Prompt**, then try to run the same steps in the Terminal of VS Code. If it does not work, then VS Code may not be recognizing the `PATH` environment variables you created.

Hope this helps
