### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by wellington1993** [alefragnani/vscode-language-pascal#50]
- Issue Type: `Bug`
- Extension Name: `pascal`
- Extension Version: `8.0.2`
- OS Version: `Linux x64 5.0.0-26-lowlatency`
- VSCode version: `1.35.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

```json 
{
	"messages": [],
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 10,
		"activateCallTime": 1,
		"activateResolvedTime": 163,
		"activationEvent": "*"
	},
	"runtimeErrors": []
}
```

**Comment by alefragnani** [comment]
Hi @wellington1993 ,

What is the issue?  Could you provide more details?

Thank you

**Comment by wellington1993** [comment]
Sure. Frequently the editor says that extension are unresponsive. 
And suggest open issue...

**Comment by alefragnani** [comment]
Well, this kind of message happens to me in two different occasions:

1. When VS Code itself is unresponsive, but it happens with _any_ extension, from time to time when working with different kind of files (pascal, JavaScript, TypeScript, C#, etc)
1. When I open _huge_ files (5Mb)

Please, check if you have any information logged on `Developer Tools / Console`

**Comment by alefragnani** [comment]
I'm closing this issue because no new comments has been made since my last question. 
Feel free to reopen/comment if the error still occurs.
