### ISSUE TITLE
gtags: directory '' not found

### ISSUE THREAD

**Issue by vintprox** [alefragnani/vscode-language-pascal#61]
After installing dependencies (GNU Global, ctags, gtags, python and pygments), reloading everything and editing *.pas, I keep getting following error in VSC:
```
Some error occured: Error: Command failed: gtags 
gtags: directory '' not found.
```

Consequently, I cannot harness extension's code navigation.

OS: Ubuntu 20.04 (Linux x64 5.4.0-31-generic)
Visual Studio Code: 1.45.1

**Comment by alefragnani** [comment]
Hi @vintprox ,

Where / when do you see this error message? Which command are you running?

The extension depends on these tools working properly (installed and configured as described in README.md) on you machine, so I suggest you to run them via shell, to make sure it is being recognised by VS Code.

1. Open a shell terminal
2. Navigate to your project's folder. 
3. Run `gtags` (no params)
4. It _should_ create 3 files named GTAGS, GPATH and GRTAGS
5. If not, something is not correct in the installation/settings
6. If yes, run `global -f relativePath/someOfYourFile.pas`
7. It _shoud_ list every method/function inside that file
8. If not, something is not correct in the installation/settings
9. If yes, for some reason VS Code doesn't recognise the settings/PATH.

I don't know about Linux, but I suppose it works similar to MacOS on this matter, so I guess some of the tips in #24 should similar to you.

Hope this helps

**Comment by alefragnani** [comment]
I'm closing this issue because no new comments has been made since my last question. 
Feel free to reopen/comment if the error still occurs.

**Comment by trey-k** [comment]
Don't think remote support is available yet based on #52 but I'm experiencing this same error trying to generate tabs on a remote SSH server. I can run `gtags` in shell and look at the results fine with `global -f file` and everything appears to be in my PATH. Extension appears to work over remote so long as I generate the tags myself but I can't find any additional logging about the error in console.

Have set GTAGSCONF, GTAGSLABEL and PYTHONPATH (suggested by #24) and have them seen by VSCode terminal, the variables are also read correctly by gtags when running with `gtags -v ` in terminal

OS: Ubuntu 20.04 (Linux 5.4.0-66-generic)
VSCode: 1.55.0

**Comment by alefragnani** [comment]
Hi @trey-k ,

It's been a long time I don't need to use SSH, but based on VS Code documentations, it should work quite similar to Docker (when it comes to how extensions should work), which I use quite frequently. And you are right, the extension does not support _any_ remotes, yet.

I don't use FreePascal and just recently started using Linux (on Docker/WSL), and I wasn't able to properly install/setup  `global` / `gtags` / `python`, so the extension can _see_ them. Could you help me on that? 

If you could provide the instructions to install/setup them on Linux/Docker environment, I would be able to test and hopefully, make the extension properly support Remotes. 

One thing you should take in consideration. Some extensions _requires_ to be installed _on remotes_, mostly because the need to access tools/resources on that remote. I'm not entirely sure, but I suppose this will be the case for the **Pascal** extension too. But that's not a big issue, because you can easily setup it on your settings.

BTW, the idea of #52 is to make the extension to support Remotes, and #66 is to support Codespaces (which uses a container/web based scenario). These are complementary issues.

Thank you

**Comment by trey-k** [comment]
@alefragnani I can walk through what I did so far, I already do have the extensions installed and running on the server even if they aren't remote compatible, let me know if I'm missing anything.

I'm on Ubuntu 20.04 so I just went with the available packages on my remote server:
```
sudo apt update
sudo apt install global exuberant-ctags python3-pygments
```

After installing I set `GTAGSCONF` and `GTAGSLABEL` environment variables as described in your own setup:

> There is no default `gtags.conf` file on Linux but I downloaded [one](https://github.com/namhyung/global/blob/master/gtags.conf) and chose to put it in my home directory because I ran into an issue after realizing `gtags` was only checking for the case-sensitive extension `.pas` by system design, so `.PAS` was also added to avoid renames. You may not have to specify `GTAGSCONF` at all!

```
export GTAGSCONF=/home/<YOUR USER>/.config/gtags.conf
export GTAGSLABEL=pygments
```

Once everything is setup you can go to your project directory and run `gtags -v` for verbose output, it should either say it's using the default configuration or the one specified by `GTAGSCONF` and that it is using the label 'pygments'. If anything seems wrong check that the programs are available in your PATH, you can see where they are installed using `which global` (where global is the program).

In addition to seeing `gtags` processing files you should now be able to use `global -f file.pas` to see generated tags, that's it!

If you need any more help figuring out installation let me know, happy to keep testing.

Add to remote settings JSON if you want to have the variables set every session:
```
{
    "terminal.integrated.env.linux": {
        "GTAGSCONF": "/home/<YOUR USER>/.config/gtags.conf",
        "GTAGSLABEL": "pygments"
    }
}
```

**Comment by alefragnani** [comment]
Hi @trey-k ,

Thanks for the detailed steps. I’ll try out, and if everything goes ok, it should be easier to update the extension to support remotes.

Stay tuned

**Comment by ansumanm** [comment]
> Hi @vintprox ,
> 
> Where / when do you see this error message? Which command are you running?
> 
> The extension depends on these tools working properly (installed and configured as described in README.md) on you machine, so I suggest you to run them via shell, to make sure it is being recognised by VS Code.
> 
> 1. Open a shell terminal
> 2. Navigate to your project's folder.
> 3. Run `gtags` (no params)
> 4. It _should_ create 3 files named GTAGS, GPATH and GRTAGS
> 5. If not, something is not correct in the installation/settings
> 6. If yes, run `global -f relativePath/someOfYourFile.pas`
> 7. It _shoud_ list every method/function inside that file
> 8. If not, something is not correct in the installation/settings
> 9. If yes, for some reason VS Code doesn't recognise the settings/PATH.
> 
> I don't know about Linux, but I suppose it works similar to MacOS on this matter, so I guess some of the tips in #24 should similar to you.
> 
> Hope this helps

Please add these debug steps to the Readme/Project page. This was very helpful in debugging my environment.

**Comment by alefragnani** [comment]
If the commands doesn't work inside VS Code, I suppose your VS Code is not being able to properly read the environment variables, where ctags/gtags paths are defined.

Are you using a _non-admin_ user, or do you have any _non-admin_ restrictions on your machine. I remember facing similar issues while using a more restrictive user.
