### ISSUE TITLE
There should be a way to disable update popup

### ISSUE THREAD

**Issue by marzojr** [alefragnani/vscode-language-pascal#65]
When the extension updates, it opens a popup to tell you what is new. Most extensions don't do that. You should either disable the update popup, or add a way to optionally disable it.

**Comment by checkdigits** [comment]
I don't agree - even VS Code itself opens a "what's new" page when it updates.

**Comment by marzojr** [comment]
VSCode is not an extension; and I dislike that behavior too. I have encountered no other extension than this and the Pascal formatter that displays such a popup after being updated.

**Comment by marzojr** [comment]
@checkdigits And if you want to go there, you can disable VSCode's update popup by setting update.showReleaseNotes, so it further reinforces that there should be a way to disable this extension's release notes as well.

**Comment by checkdigits** [comment]
"if you want to go there" lol, wow.

**Comment by alefragnani** [comment]
Hi @marzojr ,

Thank you for your suggestion, but I'll keep the current approach for now. Don't worry, the "What's New" window will appear only on new releases (patches are silent). This is not a nag window.

Hope this helps

**Comment by spartanatreyu** [comment]
I'm sorry @alefragnani, but if you don't provide a way to disable it, then it is definitely a nag window.
