### ISSUE TITLE
Add `strict` keyword to highlighting

### ISSUE THREAD

**Issue by MA-Maddin** [alefragnani/vscode-language-pascal#87]
The [`strict` visibility specifier](http://docwiki.embarcadero.com/RADStudio/Sydney/en/Classes_and_Objects_(Delphi)#Strict_Visibility_Specifiers) is not highlighted.

For example:
```
type
  TMyClass = class(TControl)
    strict private
      { strict private declarations here }
  end;
```

**Comment by alefragnani** [comment]
Hi @MA-Maddin ,

Thanks for reporting. Feel free to open a PR if you like. 

You just need to update `syntaxes/pascal.tmLanguage`, adding the new keyword.

Hope this helps
