### ISSUE TITLE
[FEATURE] - Support GitHub.dev

### ISSUE THREAD

**Issue by alefragnani** [alefragnani/vscode-language-pascal#89]
https://github.com/microsoft/vscode-docs/blob/vnext/api/extension-guides/web-extensions.md

**Comment by GitMensch** [comment]
Note: web extensions may not only be used with github.dev (like this extension is not only be usable as-is with "Microsoft Visual Studio Code" but with any vscode build and also with Theia). You may want to adjust the title (or not ;-)

**Comment by alefragnani** [comment]
Hi @GitMensch,

This issue is exclusive to the _oficial_ web versions only, which today corresponds to GitHub.dev and vscode.dev. Specially because today, the extension only supports MS Marketplace.

Any other _alternative_ (desktop or web) should be tracked separately, like in #97. The main reason for this approach is because I don't use those alternatives, yet, so I can't say it works, if I didn't test. 

Hope this helps

**Comment by alefragnani** [comment]
Depends on https://github.com/microsoft/vscode/issues/136231
