### ISSUE TITLE
[FEATURE] - adjust to make available as web extension

### ISSUE THREAD

**Issue by GitMensch** [alefragnani/vscode-language-pascal#96]
To allow use as web extension (more details at https://code.visualstudio.com/api/extension-guides/web-extensions) it maybe is enough to add the web entry point and update the package.json. Currently this extension cannot be used in web instances like vscode.dev.

**Comment by alefragnani** [comment]
Hi @GitMensch ,

This is already being tracked in #89 . Please upvote, so I’m able to see how desired/popular this feature is.

Thank you
