### ISSUE TITLE
[FEATURE] - Publish to open-vsx

### ISSUE THREAD

**Issue by GitMensch** [alefragnani/vscode-language-pascal#97]
The [Open VSX Registry](https://open-vsx.org/?search=pascal) currently doesn't ship this extension. Open VSX Registry is the default extension provider endpoint for the free build of vscode VSCodium and Eclipse Theia. It would be nice to have this extension be directly published to a free vsix repository instead of only the Microsoft Marketplace with its restrictions.

Details on the publishing can be found at https://github.com/eclipse/openvsx/wiki/Publishing-Extensions.

**Comment by alefragnani** [comment]
Hi,

I just published the new [release 9.8.0](https://github.com/alefragnani/vscode-language-pascal/milestone/23) to Open VSX.

Thank you for your patience.
